# Generated by Django 4.0.1 on 2022-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='cname',
            field=models.CharField(default='samsung', max_length=100),
        ),
    ]
