# Generated by Django 4.0.1 on 2022-02-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_image_photo_cimage_remove_photo_cname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cimage',
            new_name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='cname',
            field=models.CharField(default='samsung', max_length=100),
        ),
        migrations.CreateModel(
            name='Photocrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cimage', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mobile')),
            ],
        ),
    ]
