# Generated by Django 4.0.1 on 2022-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='compList',
            field=models.ManyToManyField(to='main.Photo'),
        ),
    ]
